### ISSUE TITLE
build help-centre using Markdown

### ISSUE THREAD

**Issue by anantdamle** [google/floody#4]
Deprecate the present Google sites based help centre and build it with markdown
use bazel/jeklly rules to compile
https://github.com/bazelbuild/bazel/blob/master/scripts/docs/jekyll.bzl

**Comment by TanveshT** [comment]
Hey @anantdamle Can I work on this?

**Comment by anantdamle** [comment]
@TanveshT Thanks for offering to help. 
Please have a look at [CONTRIBUTING](https://github.com/google/floody/blob/main/CONTRIBUTING.md) guidelines.
Once you are ready, propose a pull-request that I can review. Limit to few pages to start, we can complete this over 2-3 PRs.

**Comment by TanveshT** [comment]
Hey thanks @anantdamle, I read the `CONTRIBUTING.md`. Before starting can I get more context over the issue?

**Comment by anantdamle** [comment]
@TanveshT the current help-centre is hosted as a Google Site [here](https://sites.google.com/corp/view/floody-help/)
The expectation is: 
1.  transform the Google Sites pages as markdown pages
2. Compile the markdown into HTML pages using [Jeklly Rule](https://github.com/bazelbuild/bazel/blob/master/scripts/docs/jekyll.bzl) 
3. package the files as part of the SpringBoot application.

The pages can be markdownified gradually.
